### ISSUE TITLE
Wrong operator and colab pointers in Lesson09_Conditionals?

### ISSUE THREAD

**Issue by lechten** [GWC-DCMB/curriculum-notebooks#14]
The [PDF](https://github.com/GWC-DCMB/curriculum-notebooks/blob/main/Lessons/_Keys/pdf/KEY_Lesson09_Conditionals.pdf) for [Lesson09_Conditionals](https://github.com/GWC-DCMB/curriculum-notebooks/blob/main/Lessons/Lesson09_Conditionals.ipynb) contains condition `len(my_list) >= 10 & len(my_list) < 15`. I do not see this in the [source notebook](https://github.com/GWC-DCMB/curriculum-notebooks/blob/main/Lessons/Lesson09_Conditionals.ipynb). Instead I see `colab_type`, `id` and `outputId`. Should this be changed?

Besides, the `&` should be `and`.

**Comment by kelly-sovacool** [comment]
Hi @lechten, for each Lesson and Practice notebook, there is a corresponding Key with the answers filled in. E.g. the Key for Lesson 09 is [Lessons/_Keys/KEY_Lesson09_Conditionals.ipynb](https://github.com/GWC-DCMB/curriculum-notebooks/blob/main/Lessons/_Keys/KEY_Lesson09_Conditionals.ipynb). This structure enables instructors to teach via live-coding by filling in the blanks in the notebook as they teach, while viewing a second screen with the answers for their own reference (not shown to the learners).
