### ISSUE TITLE
String comparisons in Loops 2

### ISSUE THREAD

**Issue by sarah-haynes** [GWC-DCMB/curriculum-notebooks#20]
In the Loops 2 lesson & practice (and possibly other) notebooks we have some string comparisons using `is`, e.g.:

![image](https://user-images.githubusercontent.com/16582242/138983299-52f1d3ba-d818-4ab2-b570-a20286ac405a.png)

We should consider changing `is` to `==` instead for equality comparison (instead of identity comparison, which will only sometimes work due to string interning)

**Comment by audreydrotos** [comment]
We decided to leave the is/is not language for readability for new students.
